---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx
spec:
  parentRefs:
  - name: kong
    namespace: kong
  hostname: "nginx.{{ domain }}"
  rules:
  - matches:
    - path:
      type: PathPrefix
      value: /
    backendRefs:
    - name: nginx
      port: 8000