---
- hosts: all
  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:
    
    - name: Install python3-pip
      ansible.builtin.apt:
        name: "python3-pip"
        state: present
      become: true

    - name: Install pre-requisites
      ansible.builtin.pip:
        name:
          - kubernetes
          - pyyaml
          - jsonpatch

    - name: Check if helm exists
      ansible.builtin.command: "which helm"
      register: helm_res
      ignore_errors: true
    
    - name: Install helm
      ansible.builtin.shell: "{{ item }}"
      with_list:
        - "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        - "sudo chmod 700 get_helm.sh"
        - "./get_helm.sh"
        - "rm get_helm.sh"
      when: helm_res.rc > 0

    - name: Create ~/manifests directory if not exists
      ansible.builtin.file:
        path: "~/manifests"
        state: directory

  roles:
    - init

- hosts: k3c
  roles:
    - provision
    - apps