---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: littlelink
spec:
  selector:
    matchLabels:
      app: littlelink
  replicas: 1
  template:
    metadata:
      labels:
        app: littlelink
    spec:
      containers:
      - name: littlelink
        image: ghcr.io/techno-tim/littlelink-server:latest
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: "{{ TZ }}"
        - name: LANG
          value: "{{ LANG }}"
        - name: META_INDEX_STATUS
          value: "{{ META_INDEX_STATUS }}"
        - name: META_KEYWORDS
          value: "{{ META_KEYWORDS }}"
        - name: OG_SITE_NAME
          value: "{{ OG_SITE_NAME }}"
        - name: OG_TITLE
          value: "{{ OG_TITLE }}"
        - name: OG_DESCRIPTION
          value: "{{ OG_DESCRIPTION }}"
        - name: OG_URL
          value: "{{ OG_URL }}"
        - name: OG_IMAGE
          value: "{{ OG_IMAGE }}"
        - name: OG_IMAGE_WIDTH
          value: "{{ OG_IMAGE_WIDTH }}"
        - name: OG_IMAGE_HEIGHT
          value: "{{ OG_IMAGE_HEIGHT }}"
        - name: GA_TRACKING_ID
          value: GXXXXXXXXXX
        - name: META_TITLE
          value: "{{ META_TITLE }}"
        - name: META_DESCRIPTION
          value: "{{ META_DESCRIPTION }}"
        - name: META_AUTHOR
          value: "{{ META_AUTHOR }}"
        - name: THEME
          value: "{{ THEME }}"
        - name: FAVICON_URL
          value: "{{ FAVICON_URL }}"
        - name: AVATAR_URL
          value: "{{ AVATAR_URL }}"
        - name: AVATAR_2X_URL
          value: "{{ AVATAR_2X_URL }}"
        - name: AVATAR_ALT
          value: "{{ AVATAR_ALT }}"
        - name: NAME
          value: "{{ NAME }}"
        - name: BIO
          value: "{{ BIO }}"
        - name: FOOTER
          value: "{{ FOOTER }}"
        - name: BUTTON_ORDER
          value: "{{ BUTTON_ORDER }}"
        - name: YOUTUBE
          value: "{{ YOUTUBE }}"
        - name: GITHUB
          value: "{{ GITHUB }}"
        - name: CUSTOM_BUTTON_TEXT
          value: "{{ CUSTOM_BUTTON_TEXT }}"
        - name: CUSTOM_BUTTON_URL
          value: "{{ CUSTOM_BUTTON_URL }}"
        - name: CUSTOM_BUTTON_COLOR
          value: "#{{ CUSTOM_BUTTON_COLOR }}" #please be aware of NOT using "#" at the start of the definition
        - name: CUSTOM_BUTTON_TEXT_COLOR
          value: "#{{ CUSTOM_BUTTON_TEXT_COLOR }}" #please be aware of NOT using "#" at the start of the definition
        - name: CUSTOM_BUTTON_ALT_TEXT
          value: "{{ CUSTOM_BUTTON_ALT_TEXT }}"
        - name: CUSTOM_BUTTON_NAME
          value: "{{ CUSTOM_BUTTON_NAME }}"
        - name: CUSTOM_BUTTON_ICON
          value: "{{ CUSTOM_BUTTON_ICON }}"
        - name: TELEGRAM
          value: "{{ TELEGRAM }}"
        - name: EMAIL
          value: "{{ EMAIL }}"
        - name: EMAIL_TEXT
          value: "{{ EMAIL_TEXT }}"
        - name: EMAIL_ALT
          value: "{{ EMAIL_ALT }}"
        - name: EMAIL_ALT_TEXT
          value: "{{ EMAIL_ALT_TEXT }}"
