apiVersion: v1
kind: ConfigMap
metadata:
  name: panel-config
  namespace: {{ .Release.Namespace | quote }}
data:
  DB_PASSWORD: {{ .Values.mariadb.auth.password }}
  APP_URL: https://{{ .Values.httproute.panel }}
  APP_ENV: production
  APP_ENVIRONMENT_ONLY: "false"
  APP_TIMEZONE: {{ .Values.TZ }}
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  QUEUE_DRIVER: redis
  REDIS_HOST: {{ .Release.Name }}-redis-headless
  DB_HOST: {{ .Release.Name }}-mariadb
  DB_USERNAME: kubectyl
  DB_PORT: "3306"
  KUBER_FULLNAME: {{ include "kuber.fullname" . }}
  INGRESS_KUBER: {{ .Values.httproute.kuber }}
  INGRESS_PANEL: {{ .Values.httproute.panel }}
  {{- if .Values.panel.email }}
  LE_EMAIL: {{ .Values.panel.email }}
  {{- end }}
