apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubectyl.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
