apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/attach", "configmaps", "services", "secrets", "persistentvolumeclaims", "events", "endpoints", "pods/exec"]
  verbs: ["create", "delete", "update", "get", "watch", "exec", "list", "deletecollection"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "delete", "get"]