apiVersion: v1
kind: Service
metadata:
  name: {{ include "panel.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: panel
spec:
  ports:
  - name: web
    port: 443
  selector:
    app: panel
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuber.fullname" . }}
  labels:
    app: kuber
spec:
  ports:
  - name: http
    port: 443
  selector:
    app: kuber
