
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "kong-{{ item }}"
spec:
  gatewayClassName: kong
  listeners:
  - name: "{{ item }}-http-1"
    port: 80
    hostname: "*.{{ item }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

  - name: "{{ item }}-http-2"
    port: 80
    hostname: "{{ item }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All