---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  gatewayClassName: kong
  listeners:
  - name: http-1
    port: 80
    hostname: "*.{{ item }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

  - name: http-2
    port: 80
    hostname: "{{ item }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

  - name: https-1
    port: 443
    hostname: "*.{{ item }}"
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-tls
          kind: Secret
          group: core
  
  - name: https-2
    port: 443
    hostname: "{{ item }}"
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: domain-tls
          kind: Secret
          group: core