---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: http-1
    port: 80
    hostname: "*.{{ domain }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

  - name: http-2
    port: 80
    hostname: "{{ domain }}"
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All