---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pagenotfound
  annotations:
    konghq.com/strip-path: '{{ strip_path }}'
spec:
  parentRefs:
  - name: "kong-{{ domain }}"
  hostnames:
  - '*.{{ domain }}'
  #- "{{ domain }}" #use it only if you don't have any httproute to that domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pagenotfound
      kind: Service
      port: {{ http_port }}