#Ghost
ghostUsername: hiimluck3r
ghostBlogTitle: h2m Blog
allowEmptyPassword: false

#Castopod
castopod_redis_salt: changeme #I know it's bad
castopod_redis_password: changeme
castopod_mysql_password: changeme