#Ghost
ghostUsername: hiimluck3r
ghostBlogTitle: h2m Blog
allowEmptyPassword: false

#Castopod
castopod_redis_salt: changeme #I know it's bad
castopod_redis_password: changeme
castopod_mysql_password: changeme

#Pterodactyl
pterodactyl_panel_size: 10Gi
pterodactyl_mariadb_size: 2Gi
pterodactyl_redis_size: 1Gi