#LittleLink
littlelink_subdomain: littlelink

#NextCloud
nextcloud_subdomain: nextcloud

#Apache
apache_subdomain: apache

#Nginx
nginx_subdomain: nginx

#Kavita
kavita_subdomain: kavita

#Ghost
ghost_subdomain: ghost
ghostUsername: hiimluck3r
ghostBlogTitle: h2m Blog
allowEmptyPassword: false

#Castopod
castopod_subdomain: castopod
castopod_redis_salt: changeme #I know it's bad
castopod_redis_password: changeme
castopod_mysql_password: changeme

#Monitoring
monitoring_subdomain: grafana

#pagenotfound
pagenotfound_subdomain: '*'