#LittleLink
littlelink_subdomain: littlelink

#NextCloud
nextcloud_subdomain: nextcloud

#Apache
apache_subdomain: apache

#Nginx
nginx_subdomain: nginx

#Kavita
kavita_subdomain: kavita

#Ghost
ghost_subdomain: ghost
ghostUsername: hiimluck3r
ghostBlogTitle: h2m Blog
allowEmptyPassword: false

#Castopod
castopod_subdomain: castopod
castopod_redis_salt: changeme #I know it's bad
castopod_redis_password: changeme
castopod_mysql_password: changeme

#Monitoring
monitoring_subdomain: monitoring-grafana #the only one that is usable, can be fixed with using specific httproute with subdomain!=servicename

#pagenotfound
pagenotfound_subdomain: '*'

#dashdot
dashdot_subdomain: dashdot
DASHDOT_SHOW_HOST: false
DASHDOT_SHOW_VERSION: true
DASHDOT_ENABLE_CPU_TEMPS: false
DASHDOT_PAGE_TITLE: "dashdot."
DASHDOT_WIDGET_LIST: "os,cpu,storage,ram,network" #gpu is also available
DASHDOT_OS_LABEL_LIST: "os,arch,up_since"
DASHDOT_CPU_LABEL_LIST: "brand,model,cores,threads,frequency"
DASHDOT_STORAGE_LABEL_LIST: "brand,size,type"
DASHDOT_RAM_LABEL_LIST: "brand,size,type,frequency"
DASHDOT_NETWORK_LABEL_LIST: "type,speed_up,speed_down,interface_speed"
DASHDOT_GPU_LABEL_LIST: "brand, model, memory"

#homepage
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
homepage_subdomain: homepage
homepage_settings_yaml: |
  ---
  providers:
    openweathermap: openweathermapapikey
    weatherapi: weatherapiapikey

homepage_widgets_yaml: |
  ---
  - resources:
      cpu: true
      memory: true
      disk: /
  - search:
      provider: duckduckgo
      target: _blank

homepage_services_yaml: |
  ---
  - Arr:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
  - Media:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best
  - Infra:
    - My Third Service:
        href: http://localhost/
        description: Homepage is cool

homepage_bookmarks_yaml: |
  ---
  - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/
  - Social:
      - Reddit:
          - abbr: RE
            href: https://reddit.com/
  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/
  - Hiimluck3r:
      - Github:
        - abbr: GH
          href: https://github.com/hiimluck3r
          description: "hiimluck3r's GitHub"

#gitlab
gitlab_subdomain: gitlab
gitlab_runner_enabled: true

#gitlab-runner
runners:
   - project1|TOKEN1
   - project2|TOKEN2
   - project3|TOKEN3