#Desired
mailu: OFF | Mail-server
codeserver: OFF | web-VSCode
jellyfin: OFF | Media-server
jackett: OFF | Torrent-indexer
sonarr: OFF | PVR-for-TV-shows
radarr: OFF | PVR-for-films
lidarr: OFF | PVR-for-music
bazarr: OFF | PVR-for-subtitles
qbittorrent: OFF | Torrent-client
gitlab: OFF | GitLab
gitlab_runner: OFF | GitLab-runner
gitea: OFF | GitHub-with-a-cup-of-tea
telegram-api: OFF | Local-Telegram-API
pterodactyl: OFF | minecraft-server-panel
konga: OFF | KongIngressController-gui

#Needs to be fixed
ghost: OFF | blog-webapp