nextcloud: OFF | Cloud-suite
mailu: OFF | Mail-server
codeserver: OFF | web-VSCode
calibre: OFF | Ebook-Library
jellyfin: OFF | Media-server
jackett: OFF | Torrent-indexer
sonarr: OFF | PVR-for-TV-shows
radarr: OFF | PVR-for-films
lidarr: OFF | PVR-for-music
bazarr: OFF | PVR-for-subtitles
qbittorrent: OFF | Torrent-client
gitlab: OFF | GitLab
gitlab_runner: OFF | GitLab-runner
gitea: OFF | GitHub-with-a-cup-of-tea
telegram-api: OFF | Local-Telegram-API
linkstack: OFF | LinkTree-selfhosted
ghost: OFF | blog-webapp
pterodactyl: OFF | minecraft-server-panel
nginx: OFF | reverse-proxy/loadbalancer/httpserver
konga: OFF | KongIngressController-gui