nextcloud: OFF | Cloud-suite
calibre: OFF | Ebook-Library
linkstack: OFF | LinkTree-selfhosted
ghost: OFF | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
dashboard: OFF | kubernetes-dashboard
monitoring: OFF | prometheus+grafana