pagenotfound: ON | Simple "404" page based on nginx (listens *.domain.com)
nextcloud: OFF | Cloud-suite
kavita: OFF | Ebook Library
littlelink: OFF | Selfhosted linktree
ghost: OFF | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
monitoring: OFF | Prometheus and Grafana
castopod: OFF | Selfhost your podcast
dashdot: OFF | Your homelab server resources dashboard
homepage: OFF | Your homelab services dashboard
gitlab: OFF | git-based DevOps platform
gitlab_runner: OFF | Runner for GitLab