nextcloud: OFF | Cloud-suite
calibre: OFF | Ebook-Library
littlelink: ON | LinkTree-selfhosted
ghost: ON | blog-webapp
nginx: ON | httpserver
apache: ON | httpserver
monitoring: OFF | prometheus+grafana