nextcloud: OFF | Cloud-suite
calibre: OFF | Ebook-Library
littlelink: OFF | LinkTree-selfhosted
ghost: OFF | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
monitoring: OFF | prometheus+grafana