nextcloud: OFF | Cloud-suite
calibre: OFF | Ebook Library
littlelink: OFF | Selfhosted linktree
ghost: OFF | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
monitoring: OFF | Prometheus and Grafana