nextcloud: OFF | Cloud-suite
kavita: OFF | Ebook Library
littlelink: OFF | Selfhosted linktree
ghost: OFF | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
monitoring: OFF | Prometheus and Grafana