nextcloud: ON | Cloud-suite
calibre: ON | Ebook-Library
littlelink: ON | LinkTree-selfhosted
ghost: ON | blog-webapp
nginx: OFF | httpserver
apache: OFF | httpserver
monitoring: OFF | prometheus+grafana