YOUTUBE: ON | Video
TWITCH: OFF | Streams
TWITTER: OFF | Microblog
GITHUB: ON | IT Hub
INSTAGRAM: OFF | Photos
LINKED_IN: OFF | Job
DISCORD: OFF | Calls
FACEBOOK: OFF | Social
TIKTOK: OFF | Short Vids
CUSTOM: ON | Your custom buttons
PATREON: OFF | Subscribe based platform
TELEGRAM: ON | Messenger
STEAM: OFF | Videogames
SPOTIFY: OFF | Music
REDDIT: OFF | Popular forum
EMAIL: ON | Your email
EMAIL_ALT: ON | Alternative email button
GHOST: OFF | Web-blogging platform