YOUTUBE: ON | Video
TWITCH: ON | Streams
TWITTER: ON | Microblog
GITHUB: ON | IT Hub
INSTAGRAM: ON | Photos
LINKED_IN: ON | Job
DISCORD: ON | Calls
FACEBOOK: ON | Social
TIKTOK: ON | Short Vids
CUSTOM: ON | Your custom buttons
PATREON: ON | Subscribe based platform
TELEGRAM: ON | Messenger
STEAM: ON | Videogames
SPOTIFY: ON | Music
REDDIT: ON | Popular forum
EMAIL: ON | Your email