#Nextcloud storage capacity
nextcloud_size: 10Gi
nextcloud_psql_size: 5Gi

#Kavita storage capacity
kavita_books_size: 6Gi
kavita_manga_size: 3Gi
kavita_comics_size: 3Gi
kavita_config_size: 2Gi

#Ghost storage capacity
ghost_size: 10Gi
ghost_mysql_size: 5Gi

#Monitoring storage capacity
grafana_size: 5Gi

#Castopod storage capacity
castopod_media_size: 5Gi
castopod_mysql_size: 3Gi
castopod_redis_size: 2Gi