---
- name: Create ~/manifests/apache directory if not exists
  file:
    path: "~/manifests/apache"
    state: directory
  when: apache|default(false)|bool == true

- name: Set app and port variables for apache app
  set_fact:
    strip_path: true
    app: apache
    domain: example1.com
    http_port: 8001

- name: Render apache manifests
  template:
    src: "roles/apps/manifests/apache/{{ item }}.yaml"
    dest: "~/manifests/apache/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "deployment"
    - "service"

- name: Render apache HTTPRoute manifest
  template:
    src: "roles/apps/templates/{{ item }}.yaml.j2"
    dest: "~/manifests/apache/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "httproute"
  when: apache|default(false)|bool == true

- name: Install apache
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/apache/{{ item }}.yaml"
  with_list:
    - "deployment"
    - "service"
    - "httproute"
  when: apache|default(false)|bool == true

- name: Remove apache
  kubernetes.core.k8s:
    state: absent
    namespace: default
    src: "~/manifests/apache/{{ item }}.yaml"
  with_list:
      - "deployment"
      - "service"
      - "httproute"
  when: apache|default(false)|bool == false