---
- name: Create ~/manifests/apache directory if not exists
  file:
    path: "~/manifests/apache"
    state: directory

- name: Render apache manifests
  template:
    src: "roles/apps/manifests/apache/{{ item }}.yaml"
    dest: "~/manifests/apache/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "deployment"
    - "service"
    - "httproute"

- name: Install apache
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/apache/{{ item }}.yaml"
  with_list:
    - "deployment"
    - "service"
    - "httproute"
  when: apache|default(false)|bool == true

- name: Remove apache
  kubernetes.core.k8s:
    state: absent
    namespace: default
    src: "~/manifests/apache/{{ item }}.yaml"
  with_list:
      - "deployment"
      - "service"
      - "httproute"
  when: apache|default(false)|bool == false