---
- name: Create ~/manifests/castopod directory if not exists
  file:
    path: "~/manifests/castopod"
    state: directory

- name: Set app and port variables for castopod app
  set_fact:
    strip_path: true
    app: "{{ castopod_subdomain }}"
    domain: example1.com
    http_port: 8007

- name: Render castopod manifests
  template:
    src: "roles/apps/manifests/castopod/{{ item }}.yaml"
    dest: "~/manifests/castopod/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "secret"
    - "mariadb-statefulset"
    - "mariadb-svc"
    - "redis-cm"
    - "redis-statefulset"
    - "redis-svc"
    - "pvc"
    - "svc"
    - "deployment"

- name: Render castopod HTTPRoute manifest
  template:
    src: "roles/apps/templates/{{ item }}.yaml.j2"
    dest: "~/manifests/castopod/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "httproute"

- name: Install castopod
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/castopod/{{ item }}.yaml"
  with_list:
    - "secret"
    - "redis-cm"
    - "redis-statefulset"
    - "redis-svc"
    - "mariadb-statefulset"
    - "mariadb-svc"
    - "pvc"
    - "svc"
    - "deployment"
    - "httproute"
  when: castopod|default(false)|bool == true

- name: Remove castopod
  kubernetes.core.k8s:
    state: absent
    namespace: default
    src: "~/manifests/castopod/{{ item }}.yaml"
  with_list:
    - "httproute"
    - "deployment"
    - "redis-cm"
    - "redis-statefulset"
    - "redis-svc"
    - "mariadb-statefulset"
    - "mariadb-svc"
    - "pvc"
    - "svc"
    - "secret"
  when: castopod|default(false)|bool == false

- name: Remove persistent data (both redis and postgres)
  kubernetes.core.k8s:
    state: absent
    namespace: default
    kind: PersistentVolumeClaim
    name: "{{ item }}"
  with_list:
    - "data-castopod-redis-0"
    - "data-castopod-redis-1"
    - "data-castopod-redis-2"
    - "data-castopod-mariadb-0"
    