---
- name: Create ~/manifests/ghost directory if not exists
  file:
    path: "~/manifests/ghost"
    state: directory
  when: ghost|default(false)|bool == true

- name: Set app and port variables for ghost app
  set_fact:
    app: ghost
    http_port: 80 #the only valid port for ghost installation is 80, otherwise it gets rewritten

- name: Deploy ghost with Helm
  kubernetes.core.helm:
    name: ghost
    state: present
    chart_ref: oci://registry-1.docker.io/bitnamicharts/ghost
    release_namespace: default
    values:
      #CAUTION START
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      startupProbe:
        enabled: false
      #CAUTION END
      persistence:
        enabled: true
        size: "{{ ghost_size }}"
      ghostUsername: "{{ ghostUsername }}"
      ghostEmail: "{{ email }}"
      ghostPassword: "{{ password }}"
      ghostBlogTitle: "{{ ghostBlogTitle }}"
      ghostHost: "ghost.{{ domain }}"
      allowEmptyPassword: "{{ allowEmptyPassword }}"
      mysql:
        primary:
          persistence:
            enabled: true
            size: "{{ ghost_mysql_size }}"
          #CAUTION START
          livenessProbe:
            enabled: false
          readinessProbe:
            enabled: false
          startupProbe:
            enabled: false
          #CAUTION END
        auth:
          rootPassword: "{{ password }}"
          password: "{{ password }}"
      externalDatabase:
        password: "{{ password }}"
      service:
        type: ClusterIP
        ports:
          http: "{{ http_port }}"
          #https:
      containerPorts:
        http: 2368
        #https:
  when: ghost|default(false)|bool == true

- name: Render ghost HTTPRoute manifest
  template:
    src: "roles/apps/templates/{{ item }}.yaml.j2"
    dest: "~/manifests/ghost/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "httproute"
  when: ghost|default(false)|bool == true

- name: Apply HTTPRoute to ghost
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/ghost/{{ item }}.yaml"
  with_list:
    - "httproute"
  when: ghost|default(false)|bool == true

- name: Remove ghost with helm
  kubernetes.core.helm:
    name: ghost
    state: absent
    release_namespace: default
  when: ghost|default(false)|bool == false

- name: Remove ghost HTTPRoute
  kubernetes.core.k8s:
    name: "{{ app }}"
    state: absent
    kind: HTTPRoute
    namespace: default
  when: ghost|default(false)|bool == false