---
- name: Configure apps
  ansible.builtin.include_tasks:
    file: "{{ item }}.yml"
  with_items:
    - "pterodactyl"
    - "pagenotfound"
    - "monitoring"
    - "castopod"
    - "nginx"
    - "apache"
    - "ghost"
    - "littlelink"
    - "nextcloud"
    - "kavita"