---
- name: Create ~/manifests/nextcloud directory if not exists
  file:
    path: "~/manifests/nextcloud"
    state: directory
  when: nextcloud|default(false)|bool == true

- name: Set app and port variables for nextcloud app
  set_fact:
    strip_path: true
    app: nextcloud
    http_port: 8004

- name: Add NextCloud helm repo
  kubernetes.core.helm_repository:
    name: nextcloud
    repo_url: "https://nextcloud.github.io/helm/"
  when: nextcloud|default(false)|bool == true

- name: Deploy nextcloud with Helm
  kubernetes.core.helm:
    update_repo_cache: true
    name: nextcloud
    state: present
    chart_ref: nextcloud/nextcloud
    release_namespace: default
    values:
      #CAUTION START
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      startupProbe:
        enabled: false
      #CAUTION END
      nextcloud:
        host: "nextcloud.{{ domain }}"
        username: "{{ user }}"
        password: "{{ password }}"
      service:
        port: "{{ http_port }}"
      internalDatabase:
        enabled: false
      externalDatabase:
        enabled: true
        type: postgresql
        user: nextcloud
        password: "{{ password }}"
      postgresql:
        enabled: true
        global:
          postgresql:
            auth:
              username: nextcloud
              password: "{{ password }}"
              database: nextcloud
        primary:
          persistence:
            enabled: true
      redis:
        enabled: true
        auth:
          enabled: true
          password: "{{ password }}"
      cronjob:
        enabled: true
      persistence:
        enabled: true
        size: "{{ nextcloud_size }}"
  when: nextcloud|default(false)|bool == true

- name: Render nextcloud HTTPRoute manifest
  template:
    src: "roles/apps/templates/{{ item }}.yaml.j2"
    dest: "~/manifests/nextcloud/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "httproute"
  when: nextcloud|default(false)|bool == true

- name: Apply HTTPRoute to nextcloud
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/nextcloud/{{ item }}.yaml"
  with_list:
    - "httproute"
  when: nextcloud|default(false)|bool == true

- name: Remove nextcloud with helm
  kubernetes.core.helm:
    name: nextcloud
    state: absent
    release_namespace: default
  when: nextcloud|default(false)|bool == false

- name: Remove nextcloud HTTPRoute
  kubernetes.core.k8s:
    name: "{{ app }}"
    state: absent
    kind: HTTPRoute
    namespace: default
  when: nextcloud|default(false)|bool == false