---
- name: Create ~/manifests/nginx directory if not exists
  file:
    path: "~/manifests/nginx"
    state: directory
  when: nginx|default(false)|bool == true

- name: Set app and port variables for nginx app
  set_fact:
    strip_path: true
    app: nginx
    domain: example1.com
    http_port: 8000

- name: Render nginx manifests
  template:
    src: "roles/apps/manifests/nginx/{{ item }}.yaml"
    dest: "~/manifests/nginx/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "deployment"
    - "service"

- name: Render nginx HTTPRoute manifest
  template:
    src: "roles/apps/templates/{{ item }}.yaml.j2"
    dest: "~/manifests/nginx/{{ item }}.yaml"
    owner: "{{ user }}"
    mode: '0644'
  with_list:
    - "httproute"
  when: nginx|default(false)|bool == true

- name: Install nginx
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "~/manifests/nginx/{{ item }}.yaml"
  with_list:
    - "deployment"
    - "service"
    - "httproute"
  when: nginx|default(false)|bool == true

- name: Remove nginx
  kubernetes.core.k8s:
    state: absent
    namespace: default
    src: "~/manifests/nginx/{{ item }}.yaml"
  with_list:
      - "deployment"
      - "service"
      - "httproute"
  when: nginx|default(false)|bool == false