---
- name: Create ~/manifests/pterodactyl directory if not exists
  file:
    path: "~/manifests/pterodactyl"
    state: directory
  when: pterodactyl|default(false)|bool == true

- name: Copy pterodactyl helm directory
  copy:
    src: apps/manifests/pterodactyl/
    dest: ~/manifests/pterodactyl/
  when: pterodactyl|default(false)|bool == true

- name: Deploy pterodactyl with Helm
  kubernetes.core.helm:
    name: pterodactyl
    state: present
    chart_ref: ~/manifests/pterodactyl
    release_namespace: default
    values: "{{ lookup('template', '{{ hostvars[\"localhost\"][\"playbook_dir\"] }}/roles/apps/manifests/pterodactyl/values.yaml.j2') | from_yaml }}"
  when: pterodactyl|default(false)|bool == true

#change /etc/nginx/http.d/panel.conf to not use ssl
#php artisan p:user:make --admin=1 --name-first=User --name-last=Name --email=example@example.com --password=12345678 --username=test

- name: Remove pterodactyl with helm
  kubernetes.core.helm:
    name: pterodactyl
    state: absent
    release_namespace: default
  when: pterodactyl|default(false)|bool == false