---
- name: Create ~/manifests/pterodactyl directory if not exists
  file:
    path: "~/manifests/pterodactyl"
    state: directory
  when: pterodactyl|default(false)|bool == true

- name: Copy pterodactyl helm directory
  copy:
    src: "{{ playbook_dir }}/roles/apps/manifests/pterodactyl/"
    dest: ~/manifests/pterodactyl/
  when: pterodactyl|default(false)|bool == true

- name: Render pterodactyl manifests
  template:
    src: "{{ playbook_dir }}/roles/apps/manifests/pterodactyl/panel.conf.j2"
    dest: "~/manifests/pterodactyl/panel.conf"
    owner: "{{ user }}"
    mode: '0644'
  when: pterodactyl|default(false)|bool == true

- name: Deploy pterodactyl with Helm
  kubernetes.core.helm:
    name: pterodactyl
    state: present
    chart_ref: ~/manifests/pterodactyl
    release_namespace: default
    values: "{{ lookup('template', '{{ hostvars[\"localhost\"][\"playbook_dir\"] }}/roles/apps/manifests/pterodactyl/values.yaml.j2') | from_yaml }}"
  when: pterodactyl|default(false)|bool == true

- name: Remove pterodactyl with helm
  kubernetes.core.helm:
    name: pterodactyl
    state: absent
    release_namespace: default
  when: pterodactyl|default(false)|bool == false