---
- name: Create k3s cluster
  shell: "k3sup install --ip {{ inventory_hostname }} --user {{ user }} --no-extras --tls-san {{ kube_vip_leader_ip }} --cluster --ssh-key ~/.ssh/ansible"
  delegate_to: localhost

- name: Configure master's kubeconfig
  shell: "{{ item }}"
  with_list: #add a replica of kubeconfig to ~/.kube/config, look cluster_init.yml for example
    - "mkdir -p ~/.kube/"
    - "sudo chmod 644 /etc/rancher/k3s/k3s.yaml"
    - "sudo chown {{ user }}:{{ user }} /etc/rancher/k3s/k3s.yaml"
    - "kubectl config view --raw > ~/.kube/config" #
    - "sudo chmod 644 ~/.kube/config"
    - "sudo chown {{ user }}:{{ user }} ~/.kube/config"

- name: Create the RBAC kube-vip settings
  kubernetes.core.k8s:
    state: present
    src: https://kube-vip.io/manifests/rbac.yaml

- name: Get kube-vip containerd image
  shell: "sudo ctr image pull ghcr.io/kube-vip/kube-vip:{{ kube_vip_version }}"
  ignore_errors: true

- name: Generate kube-vip daemonSet manifest
  shell: "{{ item }} manifest daemonset \
    --interface {{ kube_vip_interface }} \
    --address {{ kube_vip_leader_ip }} \
    --inCluster \
    --taint \
    --controlplane \
    --arp \
    --leaderElection | sudo tee /var/lib/rancher/k3s/server/manifests/kube-vip.yaml"
  with_list:
    - "sudo ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:{{ kube_vip_version }} vip /kube-vip"

- name: Change localhost to node IP
  shell: "sed -i 's|127.0.0.1|{{ kube_vip_leader_ip }}|' {{ item }}"
  with_list:
    #- "/etc/rancher/k3s/k3s.yaml"
    - "~/.kube/config"