---
- name: Configurate single-node k3s cluster
  ansible.builtin.import_tasks:
    file: cluster_init.yml
  when: inventory_hostname in groups["cluster"]

- name: Configurate leader-node for k3s cluster
  ansible.builtin.import_tasks:
    file: leader_init.yml
  when: inventory_hostname in groups["leader"]

- name: Configurate quorum-nodes for k3s cluster
  ansible.builtin.import_tasks:
    file: quorum_init.yml
  when: inventory_hostname in groups["quorum"]

- name: Configurate worker-nodes for k3s cluster
  ansible.builtin.import_tasks:
    file: worker_init.yml
  when: inventory_hostname in groups["worker"]