---
- name: Check if k3sup is installed on a quorum-node
  command: "which k3sup"
  register: k3sup_res
  ignore_errors: true
  
- name: Print k3sup_res.rc
  debug:
    msg: "{{ k3sup_res.rc }}"

- name: Install k3sup on a quorum node
  shell: "{{ item }}"
  with_list:
    - "curl -sLS https://get.k3sup.dev | sh"
    - "sudo install k3sup /usr/local/bin/" 
  failed_when: k3sup_res.rc == 0
  ignore_errors: true

- name: Add quorum-node to k3s cluster
  shell: "{{ item }}"
  with_list:
    - "k3sup join --local --user {{ user }} --no-extras --server-ip {{ kube_vip_leader_ip }} --server"