---
- name: Add quorum-node to k3s cluster
  shell: "{{ item }}"
  with_list:
    - "k3sup join --ip {{ inventory_hostname }} --user {{ user }} --no-extras --server-ip {{ kube_vip_leader_ip }} --server --ssh-key ~/.ssh/ansible"