---
- name: Add worker-node to k3s cluster
  shell: "{{ item }}"
  with_list:
    - "k3sup join --ip {{ inventory_hostname }} --user {{ user }} --server-ip {{ kube_vip_leader_ip }} --server-user {{ user }} --ssh-key ~/.ssh/ansible"
  delegate_to: localhost